apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: vehicle_org
      defaultBucket: vehicle_data
      tlsSkipVerify: false
    secureJsonData:
      token: vehicle-admin-token
    isDefault: true

  - name: mssql
    type: mssql
    uid: cfc15eb7mht6oc
    access: proxy
    url: tds.cdata.com:14333
    user: smartcarhtwsaar@gmail.com
    database: GoogleCalendarSmartCar
    jsonData:
      connMaxLifetime: 14400
      encrypt: disable
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      pdcInjected: false
    secureJsonData:
      password: d5HDGKxSXFeGcHeRvUces+6s2FvpqEjtz0Z0hbpxUtsQzqL8
    isDefault: false
